#!/usr/bin/perl

eval 'exec /usr/bin/perl -w -S $0 ${1+"$@"}'
    if 0; # not running under some shell

=head1 NAME

geoip-lookup - lookup country for IP address or hostname

=head1 SYNOPSIS

 geoip-lookup [-l] <ipaddress|hostname>

=head1 DESCRIPTION

The I<geoip-lookup> program will return the country for the IP address or
hostname given as the first command line argument.
It queries uses the database in C</usr/local/geoip/Geo-IP.dat>.

By default it prints the ISO 3166 country code.  Use the C<-l> option
to print the country name.

=head1 EXAMPLE

Lookup up country for IP address 65.15.30.247

 # geoip-lookup 65.15.30.247
 United States

=head1 AUTHOR

T.J. Mather <tjmather@tjmather.com>

=cut

use strict;

use Geo::IP;
use Getopt::Std;

use Locale::Country;

my %opts;
unless (getopt('', \%opts)) {
  usage();
}

my $addr = shift || usage();

my $gi = new Geo::IP;

my $code = lc($gi->lookup_country_by_name($addr));

if ($opts{l}) {
  eval { require Locale::Country; }
    or die "Use of -l flag requires that Locale::Country is installed";
  print Locale::Country::code2country($code);
} else {
  print $code;
}
print "\n";

sub usage
{
  my $progname = $0;
  $progname =~ s,.*/,,;    # only basename left in progname
    $progname =~ s/\.\w*$//; # strip extension if any
  die "Usage: $progname [-l] <ipaddress|hostname>\n";
}
